image: registry.jiangxingai.com:5000/cicd/golang-nodejs:0.1.0

variables:
  GO111MODULE: "on"
  GOPROXY: "https://mirrors.aliyun.com/goproxy/"

stages:
  - build
  - deploy
  - deploy-harbor-review
  - deploy-harbor-iotedge

build:
  tags:
    - docker-builder
  cache:
    paths:
      - .cache
  stage: build
  before_script:
    - sed -i 's/http:\/\/gitlab\.jiangxingai\.com/..\/..\/..\/../' .gitmodules
    - git submodule sync --recursive
    - git submodule update --init --recursive

    # cache needs to be inside $CI_PROJECT_DIR
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
  script:
    - make docker-arm64
  artifacts:
    paths:
      - build/*
    expire_in: 1 day
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/

deploy:
  tags:
    - docker-builder
  stage: deploy
  environment:
    name: registry
    url: http://registry.jiangxingai.com:8080
  script:
    - make deploy-arm64
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/

deploy-harbor-review:
  tags:
    - docker-builder
  stage: deploy-harbor-review
  environment:
    name: harbor
    url: http://harbor.jiangxingai.iotedge
  script:
    - make deploy-harbor-arm64
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/

deploy-harbor-iotedge:
  tags:
    - docker-builder
  stage: deploy-harbor-iotedge
  environment:
    name: harbor
    url: http://harbor.jiangxingai.com
  script:
    - make deploy-harbor-arm64-iotedge
  when: manual
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/
