version: '3'

services:
  edgex-device-cameras:
    image: registry.jiangxingai.com:5000/edgex/device-service/cameras-ffmpeg:arm64v8-cpu-0.0.1
    container_name: edgex-device-cameras
    hostname: edgex-device-cameras
    restart: always
    volumes:
      - /tmp:/tmp
      - /data/tmpfs:/data/tmpfs
      - /sys:/sys
    command: --pm ffmpeg
    privileged: true

networks:
  default:
    external:
      name: edgex
